### ISSUE TITLE
Missing config.yaml File When Dockerizing the App

### ISSUE THREAD

**Issue by Itz-Agasta** [luismavs/ExposureStats#12]
I am attempting to dockerize the application as per issue #6, but I encountered the following error when running the container:

```bash
2024-12-23 19:08:18 
2024-12-23 19:08:18 Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.
2024-12-23 19:08:18 
2024-12-23 19:08:18 
2024-12-23 19:08:18   You can now view your Streamlit app in your browser.
2024-12-23 19:08:18 
2024-12-23 19:08:18   URL: http://0.0.0.0:8080
2024-12-23 19:08:18 
2024-12-23 19:08:27 2024-12-23 13:38:27.413 Uncaught app exception
2024-12-23 19:08:27 Traceback (most recent call last):
2024-12-23 19:08:27   File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
2024-12-23 19:08:27     exec(code, module.__dict__)
2024-12-23 19:08:27   File "/app/exposurestats/app.py", line 185, in <module>
2024-12-23 19:08:27     main()
2024-12-23 19:08:27   File "/app/exposurestats/app.py", line 126, in main
2024-12-23 19:08:27     cfg = Config.get_config("config.yaml")
2024-12-23 19:08:27           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 19:08:27   File "/app/exposurestats/config.py", line 83, in get_config
2024-12-23 19:08:27     with open(path_to_yaml, "r") as f:
2024-12-23 19:08:27          ^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 19:08:27 FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
```

## Investigation
I checked the [`.dockerignore file`](https://github.com/luismavs/ExposureStats/blob/main/.gitignore) and found that `config.yaml` is listed there. This means the `config.yaml` file is not included in the Docker build context nor present in the container.

## Request
Could you please provide guidance on the following:

1. Should the `config.yaml` file be included in the repository, or is it intentionally excluded?
2. If it is intentionally excluded, could you provide a template or example content for the `config.yaml` file so that I can create it manually?
3. Any additional instructions on how to handle the `config.yaml`  file when dockerizing the application would be appreciated.

### Issue_2: Missing `install_nbs.sh` Script
In the README, there is a section that mentions installing requirements for notebooks using the following command:
```sh
sh install_nbs.sh
```
However, the `install_nbs.sh` file is not present in the root directory of the project. Please add the `install_nbs.sh` script to the root directory.

Thank you!

**Comment by luismavs** [comment]
Hi @Itz-Agasta, thanks for the comments. I was actually just working on this project. Check the changes introduced by  PR #13, config setting done now by env vars wich will help in dockerizing.
